### ISSUE TITLE
`powmod` function returns something without the `mod` operation

### ISSUE THREAD

**Issue by erou** [wbhart/AbstractAlgebra.jl#10]
Hello, 

I do not know if this is intended, but the function `powmod` do not call `mod` if the exponent is 1.

```
julia> using AbstractAlgebra

julia> powmod(123, 1, 5)
123

julia> powmod(666, 1, 6)
666
```

This is because the `mod` function is only called during the while loop of the square and multiply strategy in `powmod`.

**Comment by wbhart** [comment]
Thanks for the report. That is indeed a bug!

**Comment by wbhart** [comment]
This will be fixed in the next version of AbstractAlgebra.

For future reference, this is my personal repo. The official repo is the one at http://github.com/Nemocas/AbstractAlgebra.jl

Unfortunately I don't know how to fix the relationship between the two repos on GitHub, so people keep reporting stuff here.
